version: "1.2"

metadata:
  name: "product_data_ingestion"
  owner: "data-eng-team"
  description: "Load sales CSV data from S3 into Snowflake"
  

datasets:

  - name: "product_data_ingestion"
    source:
      type: "s3"
      file_pattern: ".*\\.csv"
      bucket: "datalake-dev-dtrai-rawlayer-in-com-sy"

    target:
      type: "snowflake"
      database: "DRAI_INGESTION_DATABASE"
      schema: "DRAI_ING_SCHEMA"
      table: "PRODUCT_MASTER"

      stage:
        name: "DRAI_S3_EXTERNAL_STAGE_INBOUND"
        path: "product_data/"
        file_format: "DRAI_CSV_FORMAT"

      schema_definition:
        product_id: NUMBER
        product_name: VARCHAR
        category: VARCHAR
        price: FLOAT
        

    ingestion:
      method: "copy_into"
      copy_options:
        load_strategy: "DROP_AND_CREATE"  #TRUNCATE_AND_LOAD, DROP_AND_CREATE
        validation_mode: false
        purge: false
        force: false
        multi_file: true
        on_error: "CONTINUE"


audit:
  enabled: true
  database: "DRAI_INGESTION_DATABASE"  
  schema: "DRAI_ING_SCHEMA"
  table: "INGESTION_AUDIT_LOG"

 